search_customer:
    pattern: /searchCustomer
    defaults: { _controller: TeclliureInvoiceBundle:Common:searchCustomer }
    prefix:   /

search_customer_name:
    pattern: /searchCustomerName
    defaults: { _controller: TeclliureInvoiceBundle:Common:searchCustomerName }

update_prices:
    pattern: /updatePrices
    defaults: { _controller: TeclliureInvoiceBundle:Common:updatePrices }