invoice_list:
    pattern:  /invoice/list
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:index }

invoice_add:
    pattern:  /invoice/add
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:addEditInvoice }

invoice_edit:
    pattern:  /invoice/edit/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:addEditInvoice }

invoice_view:
    pattern:  /invoice/view/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:viewInvoice }

invoice_print:
    pattern:  /invoice/print/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:printInvoice }

invoice_delete:
    pattern:  /invoice/delete/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:deleteInvoice }

invoice_open:
    pattern:  /invoice/open/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:openInvoice }

invoice_close:
    pattern:  /invoice/close/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:closeInvoice }

search_customer:
    pattern: /searchCustomer
    defaults: { _controller: TeclliureInvoiceBundle:Common:searchCustomer }

search_customer_name:
    pattern: /searchCustomerName
    defaults: { _controller: TeclliureInvoiceBundle:Common:searchCustomerName }

update_prices:
    pattern: /updatePrices
    defaults: { _controller: TeclliureInvoiceBundle:Common:updatePrices }

taxes:
    resource: "@TeclliureInvoiceBundle/Controller/TaxController.php"
    type:     annotation