parameters:
    teclliure_invoice_service.class: Teclliure\InvoiceBundle\Service\InvoiceService
    teclliure_quote_service.class: Teclliure\InvoiceBundle\Service\QuoteService
    teclliure_delivery_note_service.class: Teclliure\InvoiceBundle\Service\DeliveryNoteService
    teclliure_payment_service.class: Teclliure\InvoiceBundle\Service\PaymentService
    teclliure_from_mail: 'send@example.net'

services:
  invoice_service:
      class: "%teclliure_invoice_service.class%"
      arguments:
        em: "@doctrine.orm.entity_manager"
        config: "@craue_config"
        eventDispatcher: "@event_dispatcher"
      tags:
        - { name: "knp_paginator.injectable", alias: "knp_paginator" }

  quote_service:
        class: "%teclliure_quote_service.class%"
        arguments:
          em: "@doctrine.orm.entity_manager"
          config: "@craue_config"
          eventDispatcher: "@event_dispatcher"
        tags:
          - { name: "knp_paginator.injectable", alias: "knp_paginator" }

  delivery_note_service:
        class: "%teclliure_delivery_note_service.class%"
        arguments:
          em: "@doctrine.orm.entity_manager"
          config: "@craue_config"
          eventDispatcher: "@event_dispatcher"
        tags:
          - { name: "knp_paginator.injectable", alias: "knp_paginator" }

  payment_service:
        class: "%teclliure_payment_service.class%"
        arguments:
          em: "@doctrine.orm.entity_manager"
          config: "@craue_config"

  teclliure.form.type_extension.collection:
      class: Teclliure\InvoiceBundle\Form\Extension\CollectionTypeExtension
      tags:
          - { name: "form.type_extension", alias: "collection" }

  teclliure.form.type.common:
      class: Teclliure\InvoiceBundle\Form\Type\CommonType
      arguments:
          - @doctrine.orm.entity_manager

  teclliure.form.type.invoice:
        class: Teclliure\InvoiceBundle\Form\Type\InvoiceType
        arguments:
            - @doctrine.orm.entity_manager

  teclliure.form.type.quote:
        class: Teclliure\InvoiceBundle\Form\Type\QuoteType
        arguments:
            - @doctrine.orm.entity_manager

  teclliure.form.type.delivery_note:
          class: Teclliure\InvoiceBundle\Form\Type\DeliveryNoteType
          arguments:
              - @doctrine.orm.entity_manager

  teclliure.common.mailer.subscriber:
        class: Teclliure\InvoiceBundle\Listener\CommonMailerSubscriber
        arguments:
            mailer: @mailer
            translator: @translator
            pdfGenerator: "@knp_snappy.pdf"
            templating: @templating
            config: @craue_config
            fromEmail: %teclliure_from_mail%
        tags:
            - { name: kernel.event_subscriber }
#    teclliure_invoice.example:
#        class: %teclliure_invoice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
