parameters:
    teclliure_invoice_service.class: Teclliure\InvoiceBundle\Service\InvoiceService
    teclliure_customer_service.class: Teclliure\CustomerBundle\Service\CustomerService

services:
  invoice_service:
      class: "%teclliure_invoice_service.class%"
      arguments:
        em: "@doctrine.orm.entity_manager"
  customer_service:
        class: "%teclliure_customer_service.class%"
        arguments:
          em: "@doctrine.orm.entity_manager"
  teclliure.form.type_extension.collection:
      class: Teclliure\InvoiceBundle\Form\Extension\CollectionTypeExtension
      tags:
          - { name: "form.type_extension", alias: "collection" }
  teclliure.form.type.common:
      class: Teclliure\InvoiceBundle\Form\Type\CommonType
      arguments:
          - @doctrine.orm.entity_manager
  teclliure.form.type.invoice:
        class: Teclliure\InvoiceBundle\Form\Type\InvoiceType
        arguments:
            - @doctrine.orm.entity_manager
#    teclliure_invoice.example:
#        class: %teclliure_invoice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
