parameters:
#    teclliure_invoice.example.class: Teclliure\InvoiceBundle\Example

services:
#    teclliure_invoice.example:
#        class: %teclliure_invoice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
