parameters:

services:
  teclliure.form.type.config:
        class: Craue\ConfigBundle\Form\ModifySettingsForm
        arguments:
            - @doctrine.orm.entity_manager
#    teclliure_invoice.example:
#        class: %teclliure_invoice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
