parameters:
  teclliure_customer_service.class: Teclliure\CustomerBundle\Service\CustomerService
#    teclliure_customer.example.class: Teclliure\CustomerBundle\Example

services:
  customer_service:
    class: "%teclliure_customer_service.class%"
    arguments:
      em: "@doctrine.orm.entity_manager"
      config: "@craue_config"
    tags:
      - { name: "knp_paginator.injectable", alias: "knp_paginator" }
#    teclliure_customer.example:
#        class: %teclliure_customer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
